import { ui } from "../../styles/ui";

const TYPE_LABELS = {
  reordered: "Reordered",
  rewritten: "Rewritten",
  trimmed: "Trimmed",
  reworded: "Reworded",
};

const FIELD_LABELS = {
  skills: "Skills",
  summary: "Summary",
  experience: "Experience",
  projects: "Projects",
  education: "Education",
  certifications: "Certifications",
};

export function CvDiffPanel({ changes = [], warnings = [], modelInfo }) {
  if (!changes.length && !warnings.length) return null;

  return (
    <div className="grid gap-3">
      {changes.length > 0 && (
        <div className="rounded-[10px] border border-[#E8E3D7] bg-[#FBFAF6] p-4">
          <p className={ui.eyebrow}>Changes applied</p>
          <ul className="mt-2 grid gap-2" aria-label="List of changes applied to CV">
            {changes.map((change, i) => (
              <li key={i} className="flex min-w-0 items-start gap-2.5">
                <span
                  className="mt-0.5 shrink-0 rounded-[4px] px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-[0.07em]"
                  style={{
                    fontFamily: "var(--font-mono)",
                    background: "var(--c-cobalt-50, #E6EBFF)",
                    color: "var(--c-cobalt, #1E3FFF)",
                  }}
                  aria-label={`Change type: ${TYPE_LABELS[change.type] || change.type}`}
                >
                  {TYPE_LABELS[change.type] || change.type}
                </span>
                <span className="min-w-0 text-[13px] text-[#3A3A40]">
                  <span className="font-medium text-[#0E0E10]">
                    {FIELD_LABELS[change.field] || change.field}
                    {" — "}
                  </span>
                  {change.description}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {warnings.length > 0 && (
        <div
          className="rounded-[10px] border border-[#E8E3D7] bg-[#FEF9E7] p-4"
          role="alert"
          aria-label="AI version warnings"
        >
          <p
            className="mb-2 text-[11px] font-[500] uppercase tracking-[0.08em]"
            style={{ fontFamily: "var(--font-mono)", color: "#B45309" }}
          >
            Warnings
          </p>
          <ul className="grid gap-1.5">
            {warnings.map((w, i) => (
              <li key={i} className="text-[13px] leading-relaxed text-[#92400E]">
                · {w.message}
              </li>
            ))}
          </ul>
        </div>
      )}

      {modelInfo && (
        <p
          className="text-right text-[11px] text-[#A4A4AC]"
          style={{ fontFamily: "var(--font-mono)" }}
        >
          {modelInfo.source === "ai-generated"
            ? `Generated by ${modelInfo.model}`
            : modelInfo.source === "rule-based-fallback"
            ? "AI unavailable — rule-based result"
            : "Rule-based result"}
        </p>
      )}
    </div>
  );
}
